language: ruby
script:
  - bundle exec jekyll build -d docs/
deploy:
  provider: pages
  local-dir: ./docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  fqdn: $SITE_FQDN
  on:
    branch: master